<template>
  <div id="sidebar" :style="{width: width + 'px'}">
    <div class="section header">
      <div class="banner">
        <img src="img/logo.svg" />
        <h3 class="">International HIV and AIDS Alliance Evidence map of community action on HIV, health and rights</h3>
      </div>
      <div v-if="showInfoText" class="description">
        <p>The <a href="http://www.aidsalliance.org/">International HIV/AIDS Alliance</a> works with communities in over 40 countries to take local, national and global action on HIV, health and human rights. Producing, using and applying the best available research is a critical element of the Alliance’s commitment to being an outcomes-driven and evidence-based organisation and is essential for us to deliver our programmes and influence policy effectively.</p>
        <p>This evidence map lets you explore the evidence generated by the Alliance on key HIV, health and rights interventions (horizontal axis) and outcomes (vertical axis).</p>
        <p>For more information on how the map was created and how to use it, read the User Guide [link TBD]. If you have questions please email: <a href="mailto:evidencemap@aidsalliance.org">evidencemap@aidsalliance.org</a></p>
      </div>
      <div class="info-text-button" v-on:click="toggleInfoText"><span v-if="showInfoText">Hide</span><span v-else>Show info</span></div>
    </div>
    <div class="heading">FILTER</div>
    <FilterMenu :studies="studies" :action="action" :filters="filters" />
    <div class="info" v-if="selectedCell.intervention !== null">
      <div class="section selected-intervention">
        <div class="heading">SELECTED INTERVENTION</div>
        <div class="content">{{selectedCell.intervention}}</div>
      </div>
      <div class="section selected-outcome">
        <div class="heading">SELECTED OUTCOME</div>
        <div class="content">{{selectedCell.outcome}}</div>
      </div>

      <div class="section">
        <div v-bind:class="{heading: true, animated: emphasiseChange, infinite: true, bounce: true}">STUDIES ({{numFoundStudies}} found)</div>
        <div class="study-groups">
          <StudyList title="Strong evidence (for)" :ids="studyGroups.for.high" :studiesLU="studiesLU" />
          <StudyList title="Moderate evidence (for)" :ids="studyGroups.for.moderate" :studiesLU="studiesLU" />
          <StudyList title="Low evidence (for)" :ids="studyGroups.for.low" :studiesLU="studiesLU" />
          <StudyList title="Strong evidence (against)" :ids="studyGroups.against.high" :studiesLU="studiesLU" />
          <StudyList title="Moderate evidence (against)" :ids="studyGroups.against.moderate" :studiesLU="studiesLU" />
          <StudyList title="Low evidence (against)" :ids="studyGroups.against.low" :studiesLU="studiesLU" />
        </div>
      </div>
    </div>
  </div>
</template>


<script>
import FilterMenu from './FilterMenu.vue'
import StudyList from './StudyList.vue'

export default {
  name: 'Sidebar',
  components: {
    FilterMenu,
    StudyList
  },
  props: {
    width: Number,
    outcomeInterventionLU: Object,
    selectedCell: Object,
    studiesLU: Array,
    studies: Array,
    filters: Object,
    emphasiseChange: Boolean,
    action: Function
  },
  data: function() {
    return {
      showInfoText: true
    }
  },
  computed: {
    studyGroups: function() {
      return this.outcomeInterventionLU[this.selectedCell.outcome][this.selectedCell.intervention]
    },
    numFoundStudies: function() {
      let num = this.studyGroups.for.high.length + this.studyGroups.for.moderate.length + this.studyGroups.for.low.length + this.studyGroups.against.high.length + this.studyGroups.against.moderate.length + this.studyGroups.against.low.length
      return num
    }
  },
  methods: {
    toggleInfoText: function() {
      this.showInfoText = !this.showInfoText
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#sidebar {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  background-color: #fff;
  z-index: 200;
  overflow-y: scroll;
  font-size: 14px;
  border-right: 1px solid #aaa;
  box-sizing: border-box;
}

.banner {
  display: flex;
  align-items: center;
  padding: 10px;
}
.banner img {
  width: 150px;
}
.header .description {
  line-height: 18px;
}

h3 {
  padding: 0 10px;
  margin: 0;
  font-size: 16px;
  line-height: 20px;
  color: #333;
  text-align: center;
}
.info-text-button {
  font-size: 12px;
  text-decoration: underline;
  text-align: right;
  color: #777;
  cursor: pointer;
  padding-right: 10px;
}
.section {
  padding-bottom: 20px;
}
.section.selected-intervention {
  background-color: #999;
  font-weight: bold;
}
.section.selected-outcome {
  background-color: #ddd;
  font-weight: bold;
}
.section p {
  padding: 0 10px;
}

.heading {
  text-align: center;
  background-color: #a71930;
  color: white;
  padding: 5px;
  font-weight: bold;
  font-size: 13px;
  margin-bottom: 10px;
}

.content {
  padding: 0 10px;
}
</style>
